### ISSUE TITLE
Lory has problems regarding 'slidesToScroll'

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [mercedesbenzio/SINFO-frontend-challenge#1]
The provided library of Lory has problems when using `slideToScroll` and the amount of items is not a multiple of the `slideToScroll` variable.

I fixed the issue. If you want I can paste the `lory.js` file.

**Comment by naflcosta** [comment]
Hi Ricardo, if that fix is needed and is part of your challenge solution please just include it in your zip with the final result. You can also add any comments or the fix explanation in the README file.
Thank you.
